exporter_name: products_csv
exporter_type: csv
collection: products
fields:
 - header: "gid"
   path: "_gid"
 - header: "created_at"
   path: "_created_at"
 - header: "title"
   path: "title"
 - header: "price"
   path: "price"
 - header: "seller"
   path: "seller"